### ISSUE TITLE
TypeError after installing bootstrap

### ISSUE THREAD

**Issue by antarr** [rails/cssbundling-rails#128]
I'm working on switching a project from Sprockets to Propshaft. When installing bootstrap using `rails css:install:bootstrap `

I get this error, event adding `"type": "module"` to package.json
```
Add build:css:prefix script
         run  npm pkg set scripts.build:css:prefix="postcss ./app/assets/builds/application.css --use=autoprefixer --output=./app/assets/builds/application.css" from "."
         run  yarn build:css:prefix from "."
(node:8876) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/antarr/Code/GitHub/wevote/.yarn/$$virtual/postcss-cli-virtual-af4ef3f226/0/cache/postcss-cli-npm-10.1.0-a45841d3d2-b523ab38fb.zip/node_modules/postcss-cli/index.js:3
import fs from 'fs-extra'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at external_module_.Module._load (/Users/antarr/Code/GitHub/wevote/.pnp.js:21148:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1
```

When running `yarn build:css`, I get this error
```
➜  wevote git:(asset-performance) ✗ yarn build:css
node:fs:2819
      const dev = BigIntPrototypeToString(stats.dev, 32);
                  ^

TypeError: BigInt.prototype.toString requires that 'this' be a BigInt
    at Number.toString (<anonymous>)
    at gotStat (node:fs:2819:19)
    at /Users/antarr/Code/GitHub/wevote/.pnp.js:20745:13

Node.js v18.17.1
```

**Comment by RedaBenh** [comment]
i have the same error on a new rails 7 app

**Comment by maxveldink** [comment]
Ran into this issue today. `cssbundling-rails` seems to not know about Yarn 4's Plug n Play default node linker. I changed this to the `node-modules` option and was able to get this to pass. I'll watch this issue to see if there are any updates for supporting the Yarn PNP linker.

Here's the line to add to the `.yarnrc.yml` file if you're interested in doing the same:
```yml
nodeLinker: node-modules`
```
